services:
    Enhavo\Bundle\TaxonomyBundle\Maker\MakeTaxonomy:
        arguments:
            - '@enhavo_app.maker.util'
        tags:
            - { name: 'maker.command' }

    Enhavo\Bundle\TaxonomyBundle\Filter\TaxonomyFilterType:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\TaxonomyBundle\Form\Type\TermAutoCompleteChoiceType:
        arguments:
            - '%enhavo_taxonomy.term.model.class%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\TaxonomyBundle\Form\Type\TermChoiceType:
        arguments:
            - '%enhavo_taxonomy.term.model.class%'
            - '@enhavo_taxonomy.term.repository'
        tags:
            - { name: form.type }

    Enhavo\Bundle\TaxonomyBundle\Form\Type\TermTreeChoiceType:
        arguments:
            - '%enhavo_taxonomy.term.model.class%'
            - '@enhavo_taxonomy.term.repository'
        tags:
            - { name: form.type }

    Enhavo\Bundle\TaxonomyBundle\Form\Type\TermType:
        arguments:
            - '%enhavo_taxonomy.term.model.class%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\TaxonomyBundle\Init\InitTaxonomy:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@enhavo_taxonomy.taxonomy.repository'
            - '@enhavo_taxonomy.taxonomy.factory'
            - '%enhavo_taxonomy.taxonomies%'
        tags:
            - { name: 'enhavo.init', alias: 'taxonomy'}

    enhavo_taxonomy.term.factory:
        public: true
        class: '%enhavo_taxonomy.term.factory.class%'
        arguments:
            - '%enhavo_taxonomy.term.model.class%'
            - '@enhavo_taxonomy.taxonomy.repository'

    Enhavo\Bundle\TaxonomyBundle\Form\Type\TermAutoSuggestionEntityType:
        arguments:
            - '%enhavo_taxonomy.term.model.class%'
            - '@enhavo_taxonomy.term.factory'
        tags:
            - { name: form.type }

    Enhavo\Bundle\TaxonomyBundle\Taxonomy\TaxonomyManager:
        arguments:
            - '@enhavo_taxonomy.taxonomy.repository'

    Enhavo\Bundle\TaxonomyBundle\EventListener\TermSubscriber:
        arguments:
            - '@Enhavo\Bundle\TaxonomyBundle\Taxonomy\TaxonomyManager'
        tags:
            - { name: kernel.event_subscriber }

    validator.term_unique:
        class:  Enhavo\Bundle\TaxonomyBundle\Validator\Constraints\TermUniqueValidator
        arguments:
            - '@enhavo_taxonomy.term.repository'
        tags:
            - { name: validator.constraint_validator, alias: term_unique }
